GET http://localhost:444/api/horarios/getHorarios HTTP/1.1

###

GET http://localhost:444/api/horarios/getHorario/b65faa18-f9c0-4d84-b16f-76c81b9fd14c HTTP/1.1

###

GET http://localhost:444/api/horarios/getHorariosPorCurso/a41e7a2e-6b5c-40da-ab0b-988a76e6ee18 HTTP/1.1

###

POST http://localhost:444/api/horarios/insertHorario  HTTP/1.1
content-type: application/json

{
        "idCurso": "84a946c9-83b5-417b-9b54-ad1a0f15afd5",
        "idProfesor": "662e8a39-6f19-4c37-94b3-5d3b79e80352",
        "dia": "Lunes",
        "horaInicio": "13:00",
        "horaFin": "15:00",
        "ciclo": "I"

}
###

PUT http://localhost:444/api/horarios/updateHorario/2c8e9891-ad46-4b89-b285-a6c82a1bf312  HTTP/1.1
content-type: application/json

{
        "idCurso": "84a946c9-83b5-417b-9b54-ad1a0f15afd5",
        "idProfesor": "662e8a39-6f19-4c37-94b3-5d3b79e80352",
        "dia": "Martes",
        "horaInicio": "14:00",
        "horaFin": "16:00",
        "ciclo": "II"
}

###

DELETE http://localhost:444/api/horarios/deleteHorario/9cdd3190-dbaf-42fa-a4af-5f5457f70deb HTTP/1.1
